[mypy]
python_version = 3.12
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
files = src/buscamaes/,tests/

[mypy-bot]
ignore_errors = true

[mypy-tse_scraper]
ignore_errors = true

[mypy-test_scraper]
ignore_errors = true




